### ISSUE TITLE
Androidからアクセスした場合の「初めての方へ」内の表示崩れ

### ISSUE THREAD

**Issue by Takahy** [miyacorata/SeiyuRoudokukaiLibrary#1]
**Describe the bug**
Androidスマートフォンからアクセスした場合の「初めての方へ」内の表示崩れによってGithubへの遷移が二度手間となってしまう不具合

**To Reproduce**
1. トップページ
2. 「初めての方へ」をタップ
3. 「詳しくはこちら」をタップ
4. 表示が崩れる
5. 再度「詳しくはこちら」をタップ
6. Githubへ移動する

**Expected behavior**
上記3.によって6.が発生する

**Screenshots**
1. 
<img src="https://user-images.githubusercontent.com/41819082/78849660-0ea6b480-7a50-11ea-9dc1-dfd98a82bda2.png" width="320px">

2.
<img src="https://user-images.githubusercontent.com/41819082/78849662-0fd7e180-7a50-11ea-858d-dfdccadebb16.png" width="320px">

4.
<img src="https://user-images.githubusercontent.com/41819082/78849664-10707800-7a50-11ea-8fc4-e10d71554cd2.png" width="320px">

**Smartphone (please complete the following information):**
 - Device: [V30+ L-01K]
 - OS: [Android 9]
 - Browser: [Chrome]
 - Version: [80]

**Additional context**
他環境での再現性は不明です

**Comment by miyacorata** [comment]
ご連絡ありがとうございます

モバイルのことを全く考えていないコードでしたのでコードを書き加えました おそらく解消したはずです
